kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: s2i-aikit-notebook # {"$openapi":"IMAGE_NAME"}
  labels:
    build: s2i-aikit-notebook # {"$openapi":"IMAGE_NAME"}
spec:
  triggers:
  - type: ConfigChange
  - type: ImageChange
  source:
    type: Git
    git:
      uri: https://github.com/ashahba/s2i-python-anaconda-base
      ref: ashahba/intel-aikit-v3
    contextDir: /
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: s2i-thoth-ubi8-py38:latest
      env:
      - name: THOTH_ADVISE
        value: "0"
      - name: THOTH_DRY_RUN
        value: "0"
      - name: THOTH_FROM_MASTER
        value: "0"
      - name: THOTH_ERROR_FALLBACK
        value: "1"
  output:
    to:
      kind: ImageStreamTag
      name: s2i-aikit-notebook:v0.0.1 # {"$openapi":"IMAGE_TAG"}
