apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: s2i-thoth-ubi8-py38
spec:
  lookupPolicy:
    local: false
  tags:
  - from:
      kind: DockerImage
      name: quay.io/thoth-station/s2i-thoth-ubi8-py38:latest
    name: latest
    referencePolicy:
      type: Source
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: s2i-aikit-notebook # {"$openapi":"IMAGE_NAME"}
  labels:
    build: s2i-aikit-notebook # {"$openapi":"IMAGE_NAME"}
spec:
  lookupPolicy:
    local: true
